### ISSUE TITLE
Move (or fork) dotfiles in TigerDenHackers

### ISSUE THREAD

**Issue by treznick** [ContinuityControl/dotfiles#50]
So, most of the users of these dotfiles don't have access to the organization in which they live. This means that us expats need to rely upon upstream PRs getting merged. This is fine, but I trust all of us implicitly to maintain these (that's right blackhats of the interwebs. I'm giving implicit trust to people to not bork my dotfiles.).

Question:
Should we move (or just fork) these dotfiles in [TigerDenHackers](https://github.com/TigerDenHackers)?

@jnimety @danbernier @benjaminoakes @tlball @ZachBeta @alexwilkinson @caseywatts @jhirbour @DariaNico ?

Also please `@` mention anyone who we know still uses these, but for whom I don't immediately know their github handle (e.g. Magen)

**Comment by benjaminoakes** [comment]
For what it's worth, Johnathan Magen never used these.  This repo started when @jnimety and I combined our dotfiles.  (For reference, his GitHub username is yonkeltron, but I don't think he would be interested in this conversation.)

Regardless, we're all very familiar with this config, and I expect many of us to continue using it.  There are a lot of benefits to shared maintenance since we have built a community around these dotfiles.  (There are downsides too, since not everyone will agree on everything, obviously.)

Anyway, I don't believe I have access to TigerDenHackers.  If we do change stewardship to that organization, could I be granted access, please?

**Comment by treznick** [comment]
You not having access was a clear oversight! You now have it, although all it has now is our little hubot for our expats slack (which, btw, if you want access to, shoot me an email).

**Comment by treznick** [comment]
Couple of things I've found that might implicate the conversation in favor of having a community fork:
1. We don't need specific branding-associated `rsp` aliases, like we've defined in the `.zshrc`, but those tigers still at continuity might need them
2. If you're doing local development on OS X, and you've got a passphrase for your ssh keys to github, then you'll need to authenticate to them each time you need to touch github. This may not be a bad thing (inconvenience correlates strongly with better security), but it's the result of the `tmux.conf` setting the `SSH_AUTH_SOCK` value from `~/ssh/ssh_auth_sock`, which gets set when you `ssh` into pairing, as defined here:
   `~/.ssh/rc`

```
#!/bin/bash
if test "$SSH_AUTH_SOCK" ; then
  ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi
```

My shell skills are fairly paltry, so if someone has a better suggestion to avoid this other than commenting this line in `~/.tmux.conf`

```
set-environment -g 'SSH_AUTH_SOCK' ~/.ssh/ssh_auth_sock
```

then I'm all ears.

cc @jhirbour @jnimety @benjaminoakes

**Comment by benjaminoakes** [comment]
I have a solution for the SSH key issue. I'll try to post it later.

**Comment by jhirbour** [comment]
@treznick I was going to comment on "If you're doing local development on OS X, and you've got a passphrase for your ssh keys to github, then you'll need to authenticate to them each time you need to touch github." 

But @benjaminoakes crushed it with his PR.
